name: My Target Workflow

on:
  workflow_dispatch:   
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
       parameter1: ${{ github.event.client_payload.parameter1 }}
       parameter2: ${{ github.event.client_payload.parameter2 }}
    steps:
      - uses: actions/checkout@v3 
      - name: Print parameters
        run: |
          echo $parameter1
          echo $parameter2
      
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo workflow name
        run: |
          echo "This is target workflow"
          echo""
          echo "This is triggered by Source workflow...."
          sleep 10  
